#Requires -Version 5.1
$ErrorActionPreference = "Stop"

if ($args.Count -lt 2) {
    Write-Host "Usage: .\dbmate.ps1 <database> <dbmate-command> [args...]"
    Write-Host "Example: .\dbmate.ps1 pgsql up"
    exit 1
}

$Database   = $args[0]
$DbmateArgs = $args[1..($args.Count - 1)]

# Get the directory where this script lives
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Build migrations dir correctly
$migrationsDir = Join-Path -Path $scriptDir -ChildPath "$Database\migrations"

if (-not (Test-Path $migrationsDir)) {
    Write-Error "Migrations directory not found: $migrationsDir"
    exit 1
}

# Credential resolution, matching database/dbmate.sh so the two do not drift:
#
#   1. DATABASE_URL  — dbmate's own convention
#   2. POSTGRES_URL  — what the app and the minion-suite-db Secret use
#   3. Doppler       — last resort
#
# Doppler is no longer the first choice. The minions database credential is
# generated by the minion-suite-infra Pulumi stack and written straight into the
# k8s Secret as POSTGRES_URL; it is deliberately not round-tripped through
# Doppler. Fetching DB_* from mcp-minions/prd therefore points at a different
# database than the one the app runs against.
if ($env:DATABASE_URL) {
    # Already set — use as-is.
}
elseif ($env:POSTGRES_URL) {
    $env:DATABASE_URL = $env:POSTGRES_URL
}
else {
    $dbUser     = doppler secrets get DB_ADMIN    --plain --project mcp-minions --config prd
    $dbPassword = doppler secrets get DB_PASSWORD --plain --project mcp-minions --config prd
    $dbHost     = doppler secrets get DB_HOST     --plain --project mcp-minions --config prd
    $dbPort     = doppler secrets get DB_PORT     --plain --project mcp-minions --config prd
    $dbName     = doppler secrets get DB_NAME     --plain --project mcp-minions --config prd

    if (-not $dbHost) {
        Write-Error "No database credentials found. Set DATABASE_URL or POSTGRES_URL, or make DB_* available in Doppler mcp-minions/prd."
        exit 1
    }

    # URL-encode user and password in case they contain special characters
    $dbUserEncoded     = [System.Uri]::EscapeDataString($dbUser)
    $dbPasswordEncoded = [System.Uri]::EscapeDataString($dbPassword)

    $sslMode = if ($env:DB_SSLMODE) { $env:DB_SSLMODE } else { "require" }
    $env:DATABASE_URL = "postgres://${dbUserEncoded}:${dbPasswordEncoded}@${dbHost}:${dbPort}/${dbName}?sslmode=${sslMode}"
}

# Run dbmate with migrations directory
dbmate --migrations-dir "$migrationsDir" --migrations-table "minions.schema_migrations" @DbmateArgs
