apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minion-suite-repos
  labels:
    app.kubernetes.io/name: minion-suite
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
